### PR TITLE
Fix title case string , package wpf, path post build event

### PR DESCRIPTION
**Pull request by chuongmep**
May be it will be better if change to title case : 
Some pull request include : 
- [x] Fix nuget package xceed.wpf.toolkit to new version
- [x] Fix post build event to can build all computer with other user
- [x] Improve Name Title Case package look better.
Before
DynamoSandbox_p1eW1It3Ps
After Change
image

Post build event may be should : 
```
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "C:\Users\JohnPierson\AppData\Roaming\Dynamo\Dynamo Core\2.12\packages\Monocle\bin"
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "C:\Users\JohnPierson\AppData\Roaming\Dynamo\Dynamo Core\2.13\packages\Monocle\bin"
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "C:\Users\JohnPierson\AppData\Roaming\Dynamo\Dynamo Core\2.14\packages\Monocle\bin"
```
Change To 
```
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "$(AppData)\Dynamo\Dynamo Core\2.12\packages\Monocle\bin"
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "$(AppData)\Dynamo\Dynamo Core\2.13\packages\Monocle\bin"
if $(ConfigurationName) == Release copy "$(ProjectDir)bin\Release\*.dll" "$(AppData)\Dynamo\Dynamo Core\2.14\packages\Monocle\bin"
```

### CODE REVIEW

**Review by johnpierson — CHANGES_REQUESTED** [review]
revert back to lower case per [style guidelines](https://github.com/johnpierson/MonocleForDynamo/blob/master/!Documentation/monocleStyleGuide.png)

**Review by johnpierson — APPROVED** [review]
@chuongmep , I revised some of the code to reflect the monocle style choices and dependency issues. but other than that, the post-build looks great.

**Comment by chuongmep** [comment]
I think you should update style in the readme of the collaboration why show lower case, surely someone will come later doing the same thing as me, i haven't seen anything about title case to sync with the theme, but it is a new thing for me and interesting, thanks for your info.

**Comment by johnpierson** [comment]
Good idea! Updated now too.
https://github.com/johnpierson/MonocleForDynamo#monocle-style-guide

Apologies for that confusion as monocle has primarily been managed by just me for quite some time. So none of that has came up

**Pull request merged**
